# ~/.config/hypr/hyprland.conf

##############################
# DEFAULT PROGRAMS
##############################
$menu = walker
$terminal = kitty
$fileManager = dolphin
$internetBrowser = zen-browser

##############################
# SOURCING
##############################
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/layouts.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/input.conf

