
##############################
# GENERAL WINDOW RULES
##############################

# Suppress maximize requests from all apps
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

# Fix XWayland drag issues
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# hyprland-run floating terminal
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Quickshell popup manager — parked off-screen at -5000,-5000
windowrule {
    name = qs-master
    match:title = ^(qs-master)$

    float = yes
    move = -5000 -5000
}

# Zen Browser Picture-in-Picture — pin across all workspaces
windowrule {
    name = pip
    match:class = ^(zen)$
    match:title = ^(Picture-in-Picture)$

    float = yes
    pin = yes
    size = 640 360
}

# Zen Browser transparency
windowrule {
    name = zen-transparency
    match:class = ^(zen)$
    # focus, no_focus
    opacity = 0.8 0.8
}

# Chromium Browser transparency
windowrule {
    name = chromeium-transparency
    match:class = ^(chrome.*)$
    opacity = 0.8 0.8
}
